backend:
  name: git-gateway
  branch: main
media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pt_blog"
    label: "Blog (PT)" # Used in the UI
    folder: "content/pt/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "string" }
      - { label: "Postado", name: "posted", widget: "datetime", format: "x" }
      - { label: "Ícone", name: "icon", widget: "image", choose_url: true }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "NFE", name: "nfe", widget: "boolean", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
  - name: "en_blog"
    label: "Blog (EN)" # Used in the UI
    folder: "content/en/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Posted", name: "posted", widget: "datetime", format: "x" }
      - { label: "Icon", name: "icon", widget: "image", choose_url: true }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "NFE", name: "nfe", widget: "boolean", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pt_jogos"
    label: "Jogos (PT)" # Used in the UI
    folder: "content/pt/jogos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "string" }
      - { label: "Aviso", name: "warning", widget: "string", required: false }
      - { label: "Postado", name: "posted", widget: "datetime", format: "x" }
      - { label: "Ícone", name: "icon", widget: "image", choose_url: true }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "NFE", name: "nfe", widget: "boolean", required: false }
      - { label: "Instruções", name: "instructions", widget: "markdown" }
      - { label: "Sobre", name: "about", widget: "markdown" }
      - {
          label: "Links",
          name: "links",
          widget: "list",
          minimize_collapsed: true,
          fields:
            [
              { label: "Texto", name: "text", widget: "string" },
              { label: "Link", name: "link", widget: "string" },
            ],
        }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
